# Generated by Django 4.1 on 2022-08-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
